### ISSUE TITLE
Some issue after latest release?

### ISSUE THREAD

**Issue by sjmiller609** [DataDog/synthetics-test-automation-github-action#80]
I'm not sure if this in on my end yet, but our pipelines started with this error this morning.

```
 Unable to resolve actions. Repository not found: datadog/synthetics-ci-github-action.
```
 
I notice you have a new release, maybe the releases got messed up somehow? We were on 0.3.0, but switched to 0.4.0 to try and fix but didn't work.

```
      - name: Run Datadog Synthetics tests (Conformance test UK and US pre-prod)
        uses: DataDog/synthetics-ci-github-action@v0.4.0
        with:
          api_key: ${{ secrets.DD_API_KEY }}
          app_key: ${{ secrets.DD_APP_KEY }}
          public_ids: 'omitted'
```
